spring:
  application:
    name: discovery-server
  config:
     import: optional:configserver:http://config-server:8888
  profiles:
    active: default
    
# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

---
spring:
  config:
    activate:
      on-profile: default
    import: optional:configserver:http://config-server:8888

