spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:config-server:8888


---
spring:
  config:
    activate:
      on-profile: default
    import: optional:configserver:http://config-server:8888
